### PR TITLE
required plots! 

### PR DESCRIPTION
**Pull request by osamamala**
absdesit1
absdesit2
abkeff-keff
@andrewryh

### CODE REVIEW

**Comment by andrewryh** [comment]
@osamamala 
Your first PR, congratulations! :dancer: 

Looks good, just add the caption for each plot (e.g. last plot is an absolute error for Keff?) and I will merge it.

P.S. And looks like for last plot units are not pcm (pcm=1E-5), please, check it out. It should be at least few pcm absolute error (likely 40-100pcm because for your simulations statistical error from SERPENT was about 35-45pcm).

Thanks

**Review by andrewryh — CHANGES_REQUESTED** [review]
Please, keep plots in the folder **doc**

**Comment by osamamala** [comment]
absdesit2
abkeff-keff
absdesit1

**Comment by katyhuff** [comment]
looking very interesting!

**Comment by osamamala** [comment]
Thank you Prof.Huff @katyhuff

**Pull request merged**
